config/routes.rb
RubyAiWeb::Application.routes.draw do
  devise_for :users

  root 'static_pages#home'
  resources :users

  match '/about', to: 'static_pages#about', via: 'get'

  match '/experiences/genetic_typer', to: 'experiences#genetic_typer', via: 'get'
  match '/experiences/genetic_typer_run', to: 'experiences#genetic_typer_run', via: 'post'

  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :recoverable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :validatable
  before_save { self.email = email.downcase }

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end
end

app/controllers/experiences_controller.rb
class ExperiencesController < ApplicationController

	GA_MAX_GEN = 2000
	GA_MAX_POP = 300

	def genetic_typer_run
		@num_gen = params[:num_gen].to_i
		@num_gen = GA_MAX_GEN if @num_gen > GA_MAX_GEN
		@num_gen = 1 if @num_gen < 1
		@num_pop = params[:num_pop].to_i
		@num_pop = GA_MAX_POP if @num_pop > GA_MAX_POP
		@num_pop = 1 if @num_pop < 1
		@sentence = params[:sentence]
		@mutation_rate = params[:mutation_rate].to_f
		@mutation_rate = 100 if @mutation_rate > 100
		@mutation_rate = 0 if @mutation_rate < 1

		ga = GeneticTyper::GeneticAlgorithm.new(@sentence, @num_pop, @num_gen, @mutation_rate)
		@first_generation = ga.population.inject("") { |result, dna| result << dna.genes << '\n' }
		start = Time.now
		ga.run
		@time = Time.now - start
		@last_generation = ga.population.inject("") { |result, dna| result << dna.genes << '\n' }

		respond_to do |format|
			format.html
			format.js
		end
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    puts "CREATE UUUUUUSSSERRR ***********"
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to RubyAiWeb!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  private
  def user_params
    params[:name] = "birthdayparty"
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/experiences_helper.rb
module ExperiencesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/experiences/genetic_typer.html.erb
<h1>Genetic Typer</h1>
<div>
  <p>
    Genetic algorithm are basically a way to evolve an algorithm through iterations.
    The algorithm is based on 4 steps:
    <ul>
      <li>Calculate the fitness of each "individual"</li>
      <li>Create a mating pool accordingly</li>
      <li>Breed</li>
      <li>Mutate</li>
    </ul>
  </p>

  <p>
    The following example is based on an example from <a href="http://natureofcode.com/book/chapter-9-the-evolution-of-code/">Nature Of Code</a>.
    <br/> All credits are given there.
  </p>
  <p>
    By tweaking the values, you should be able to test and see what is a good deal between the size of the population/number of generations/mutation rate.
  </p>
</div>
<br/>
<%= form_tag('/experiences/genetic_typer_run', remote: true) do %>
  <div class="row">
    <div class="span3"><%= label :sentence, 'Type in a sentence to find:' %></div>
    <div class="span6"><%= text_field_tag :sentence, 'to be or not to be' %></div>
  </div>

  <div class="row">
    <div class="span3"><%= label :num_pop, 'Size of population (max 300) :' %></div>
    <div class="span3"><%= number_field_tag :num_pop, nil, value: 150, min: 1, max: 300 %></div>
  </div>  

  <div class="row">
    <div class="span3"><%= label :num_gen, 'Number generations (max 2000) :' %></div>
    <div class="span3"><%= number_field_tag :num_gen, nil, value: 1000, min: 1, max: 2000 %></div>
  </div>

  <div class="row">
    <div class="span3"><%= label :mutation_rate, 'Mutation rate (0-100) :' %></div>
    <div class="span3"><%= number_field_tag :mutation_rate, nil, value: 0.02, step: 0.01, min: 0, max: 100 %></div>
  </div>

  <br/>
  <div class="row">
    <div class="span1"> <%= submit_tag("Run", id: "run") %></div>
    <br/>
    <div class="span2" id="running" style="display: none">Running ...</div>
    <div class="span3" id="time" style="display: none"></div>
  </div>
<% end %>

<div class="row">
  <div class="span5">
    <textarea id="first_generation" rows="10"></textarea>
  </div>
  <div class="span5 offset2">
    <textarea id="last_generation" rows="10"></textarea>
  </div>
</div>

app/views/experiences/genetic_typer_run.html.erb
<p>Num pop: <%= @num_pop %></p>
<p>Num generations: <%= @num_gen %></p>
<p>Time to generate: <%= @time %></p>
<p>First Generation:</p>
<% @first_generation.each do |genes| %>
<%= genes %> </br>
<% end %>
</br></br>
<p>Last Generation: </p>
<% @last_generation.each do |genes| %>
<%= genes %> </br>
<% end %>

app/views/experiences/genetic_typer_run.js.erb
$('#first_generation').text("<%= @first_generation %>");
$('#last_generation').text("<%= @last_generation %>");
$('#running').hide();
$('#time').text("It ran for <%= @time %> seconds").show();
$('body').css('cursor', 'default');

app/views/layouts/_footer.html.erb
<footer class="footer">

  <small>
    <%= link_to image_tag('ruby.png', alt: 'Rails'), root_path %>
    <%= link_to 'RubyAIWeb', root_path %>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "RubyAiWeb", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "About",    about_path %></li>
          <% if user_signed_in? %>
              <li><%= link_to "Users", '#' %></li>
              <li id="fat-menu" class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Account <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Profile", current_user %></li>
                  <li><%= link_to "Settings", '#' %></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to "Sign out", destroy_user_session_path, method: "delete" %>
                  </li>
                </ul>
              </li>
          <% else %>
              <li><%= link_to "Sign in", new_user_session_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
      </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RubyAiWeb</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
</head>
<body>
<%= render 'layouts/header' %>

<div class="container">
  <%  #TODO add actual style or move these? %>
  <% if notice %>
    <p class="notice"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert"><%= alert %></p>
  <% end %>

  <%= yield %>

  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
</div>

</body>
</html>

app/views/shared/_error_message.html.erb
<% if @user.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-error">
        The form contains <%= pluralize(@user.errors.count, "error") %>.
      </div>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/static_pages/about.html.erb
<h1>About</h1>

<p>
  A real About page will eventually come. <br>
  This site is supposed to be a kind of show-room of projects, examples of AI written in Ruby.
  Feel free to contribute or get in touch for ideas!
</p>

app/views/static_pages/contact.html.erb
<h1>Contact</h1>

<p>No contacts yet ...</p>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
  <h1>Welcome to RubyAiWeb</h1>

  <h3>
    <%= link_to 'The show-room for AI written in Ruby!' %>
  </h3>
  <br/>
  <% if !user_signed_in? %>
    <%= link_to 'Sign up now!', new_user_registration_path, class: 'btn btn-large btn-primary' %>
  <% else %>
    <%= link_to "User's page", current_user, class: 'btn btn-large btn-primary' %>
  <% end %>
</div>

<div class="row">
  <div class="span4 offset3">
    <h2>Experiments <%= image_tag "experiments.png", alt: "Experiments", size: "50" %></h2>
    <p><%= link_to "Genetic Typer", experiences_genetic_typer_path %></p>
  </div>

  <div class="span3">
    <h2>Games <%= image_tag "game_board.png", alt: "Games", size: "50" %></h2>
    <p>Coming ...</p>
  </div>
</div>

app/views/users/index.html.erb
<h1>All Users</h1>
<% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %>
    </li>
<% end %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">

    <%= render 'shared/error_message' %>

    <%= form_for(@user) do |f| %>

        <%= f.label :name %>
        <%= f.text_field :name %>

        <%= f.label :email %>
        <%= f.text_field :email %>

        <%= f.label :password %>
        <%= f.password_field :password %>

        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation %>

        <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<h1>User's page</h1>
<div class="row">
  <aside>
    <section>
      <h1>
        <p>Email: <%= @user.email %></p>
        <p>Name: <%= @user.name %></p>
      </h1>
    </section>
  </aside>
</div>